### ISSUE TITLE
'MSVCCompiler' object has no attribute 'compiler_so'

### ISSUE THREAD

**Issue by ozgucbertug** [jrterven/KinZ-Python#1]
First of all, thank you for making this publicly available. When I'm trying to compile the library in Windows, I repeatedly get an AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'. How can I circumvent this problem? Any suggestions are welcomed. Please see the output below:

(kinz) C:\Users\Ozguc\Documents\GitHub\KinZ-Python>pip install .
Processing c:\users\ozguc\documents\github\kinz-python
Requirement already satisfied: pybind11>=2.3 in c:\users\ozguc\anaconda3\envs\kinz\lib\site-packages (from kinz==1.0) (2.6.1)
Building wheels for collected packages: kinz
  Building wheel for kinz (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Ozguc\anaconda3\envs\kinz\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ozguc\\AppData\\Local\\Temp\\pip-req-build-djy1o167\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ozguc\\AppData\\Local\\Temp\\pip-req-build-djy1o167\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Ozguc\AppData\Local\Temp\pip-wheel-56wphlgu'
       cwd: C:\Users\Ozguc\AppData\Local\Temp\pip-req-build-djy1o167\
  Complete output (34 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Ozguc\AppData\Local\Temp\pip-req-build-djy1o167\setup.py", line 110, in <module>
      zip_safe=False,
    File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\Ozguc\AppData\Local\Temp\pip-req-build-djy1o167\setup.py", line 85, in build_extensions
      if '-Wstrict-prototypes' in self.compiler.compiler_so:
  AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
  ----------------------------------------
  ERROR: Failed building wheel for kinz
  Running setup.py clean for kinz
Failed to build kinz
Installing collected packages: kinz
    Running setup.py install for kinz ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Ozguc\anaconda3\envs\kinz\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ozguc\\AppData\\Local\\Temp\\pip-req-build-djy1o167\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ozguc\\AppData\\Local\\Temp\\pip-req-build-djy1o167\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Ozguc\AppData\Local\Temp\pip-record-_001jsy7\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Ozguc\anaconda3\envs\kinz\Include\kinz'
         cwd: C:\Users\Ozguc\AppData\Local\Temp\pip-req-build-djy1o167\
    Complete output (36 lines):
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Ozguc\AppData\Local\Temp\pip-req-build-djy1o167\setup.py", line 110, in <module>
        zip_safe=False,
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
        _build_ext.run(self)
      File "C:\Users\Ozguc\anaconda3\envs\kinz\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\Ozguc\AppData\Local\Temp\pip-req-build-djy1o167\setup.py", line 85, in build_extensions
        if '-Wstrict-prototypes' in self.compiler.compiler_so:
    AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Ozguc\anaconda3\envs\kinz\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ozguc\\AppData\\Local\\Temp\\pip-req-build-djy1o167\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ozguc\\AppData\\Local\\Temp\\pip-req-build-djy1o167\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Ozguc\AppData\Local\Temp\pip-record-_001jsy7\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Ozguc\anaconda3\envs\kinz\Include\kinz' Check the logs for full command output.

**Comment by JoeyJoy16** [comment]
I also have this problem. Have you solve it already?

**Comment by QiuJunning** [comment]
I also have this problem. Have you solve it already?

**Comment by CharliPosner** [comment]
Did anyone manage to solve this?

**Comment by ytop0386** [comment]
Did anyone know how to solve this problem?

**Comment by mariochamdjoko** [comment]
Did anyone manage to solve this?
