### ISSUE TITLE
'kinz.Kinect' object has no attribute 'get_bodies'

### ISSUE THREAD

**Issue by ma-nu-ell** [jrterven/KinZ-Python#4]
Successfully installed kinz-1.0 with optional bodytracking functionality. 
Did run the command: 'CFLAGS="-l:libk4abt.so -DBODY" pip install .'

All demos do run well except the body_tracking_demo.py 

~/Projects/KinZ-Python$ python3 demos/body_tracking_demo.py 
Kinect started successfully!!
Could not read depth image
Traceback (most recent call last):
  File "demos/body_tracking_demo.py", line 164, in <module>
    main()
  File "demos/body_tracking_demo.py", line 43, in main
    bodies = kin.get_bodies()
AttributeError: 'kinz.Kinect' object has no attribute 'get_bodies'

Any idea?

**Comment by BigTsung** [comment]
Same here. I traced code "kinect.cpp" and I found this code support get_bodies function. Any clues? Thanks.

**Comment by ma-nu-ell** [comment]
Maybe it's because of the time lag between the color and depth cameras.

**Comment by BigTsung** [comment]
In my opinion, the function 'get_bodies' is defined in #ifdef BODY. So if not define BODY first the function will not work after building.

**Comment by gengauss** [comment]
I have the same problem. How to deal with it? @ma-nu-ell

**Comment by gengauss** [comment]
> In my opinion, the function 'get_bodies' is defined in #ifdef BODY. So if not define BODY first the function will not work after building.

Can you solve it yet? Thanks

**Comment by ma-nu-ell** [comment]
Maybe that will solve it.I guessed that the depth cam startS with a delay and for the first images in loop there are no depth informations for the get_bodies function.
-------- Ursprüngliche Nachricht --------Von: Anh Nguyen ***@***.***> Datum: 01.06.22  05:48  (GMT+01:00) An: jrterven/KinZ-Python ***@***.***> Cc: Manuel Seip ***@***.***>, Mention ***@***.***> Betreff: Re: [jrterven/KinZ-Python] 'kinz.Kinect' object has no attribute 'get_bodies' (Issue #4) 

In my opinion, the function 'get_bodies' is defined in #ifdef BODY. So if not define BODY first the function will not work after building.

Can you solve it yet? Thanks

**Comment by gengauss** [comment]
@ma-nu-ell Does it mean I need to set up the first images? Or are there anyways to force the function skip the first images?

**Comment by ma-nu-ell** [comment]
Sorry for the late answer. I skipped Kinz for my project. Cheers
